-- Migration 045: Add generation_reason to radar_narratives
--
-- Distinguishes narratives generated by the fallback trigger (single interpreted
-- signal, no movement, no prior narrative) from those generated by standard
-- triggers (movement, signal burst, pressure spike).
--
-- Fallback narratives are displayed as "preliminary observation" in the UI to
-- ensure honest representation — a single weak signal should not appear as
-- confirmed strategic intelligence.

ALTER TABLE radar_narratives
  ADD COLUMN IF NOT EXISTS generation_reason TEXT;

COMMENT ON COLUMN radar_narratives.generation_reason IS
  'Trigger that caused generation: null = standard triggers, ''fallback'' = single-signal no-movement fallback.';
