-- Migration 052: strategic_actions
-- Priority-ranked action queue generated by GPT-4o from competitor_contexts + movements.
-- Regenerated daily at 09:30 UTC. Operators can mark actions done or dismiss them.
-- Open actions are replaced on each generation run; done/dismissed rows are preserved.

CREATE TABLE IF NOT EXISTS strategic_actions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id           UUID NOT NULL,
  action_type      TEXT NOT NULL,   -- defensive | offensive | monitoring
  urgency          TEXT NOT NULL,   -- high | medium | low
  priority         INTEGER NOT NULL, -- 1 = highest priority within the org's queue
  title            TEXT NOT NULL,
  description      TEXT NOT NULL,
  rationale        TEXT,
  competitor_names TEXT[] NOT NULL DEFAULT '{}',
  status           TEXT NOT NULL DEFAULT 'open',  -- open | done | dismissed
  generated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS strategic_actions_org_status_idx
  ON strategic_actions(org_id, status);

CREATE INDEX IF NOT EXISTS strategic_actions_org_priority_idx
  ON strategic_actions(org_id, priority)
  WHERE status = 'open';
