// ── Knowledge Panels Content Library ──────────────────────────────────────────
//
// 38 slides across 3 types: history, feature, science.
// No React imports — pure content library.

export type SlideType = "history" | "feature" | "science";

export type VisualKey =
  // History
  | "store" | "camera" | "phone" | "glass" | "deal"
  | "clock" | "server" | "map" | "book" | "chart"
  // Feature
  | "radar-gravity" | "signal-detection" | "movement-detection"
  | "sector-intelligence" | "weekly-brief" | "pressure-index"
  | "selector-repair" | "signal-velocity" | "confidence-model"
  | "page-classes" | "critical-alert" | "momentum-states"
  // Science
  | "brain" | "asymmetry" | "loss-aversion" | "availability"
  | "pattern" | "vigilance" | "sensemaking" | "confirmation"
  | "dopamine" | "planning-fallacy" | "working-memory" | "exposure";

export type KnowledgeSlide = {
  id: string;
  type: SlideType;
  badge: string;
  accent: string;
  era: string;
  visual: VisualKey;
  title: string;
  hook: string;
  points: [string, string, string];
  cta: string;
  priority: number;
};

export const KNOWLEDGE_SLIDES: KnowledgeSlide[] = [
  // ── HISTORY ──────────────────────────────────────────────────────────────────

  {
    id: "hist-prehistoric",
    type: "history",
    badge: "HISTORY",
    accent: "#6366f1",
    era: "200,000 BCE",
    visual: "glass",
    title: "The First Competitive Intelligence Network",
    hook: "Prehistoric tribes stationed sentinels on high ground — not to watch prey, but to watch each other. The ones who detected rival movements first survived.",
    points: [
      "Homo sapiens developed neural architecture for detecting intentional movement — distinguishing a rival group's advance from environmental noise at over one kilometre",
      "Early settlements were positioned for observation, not defence: elevated ground, sight lines to water sources, and chokepoints where movement became visible before contact",
      "The tribes that failed were not weaker — they were less informed. Advance notice mattered more than superior weapons",
    ],
    cta: "The principle hasn't changed — only the signal medium.",
    priority: 1,
  },

  {
    id: "hist-egypt",
    type: "history",
    badge: "HISTORY",
    accent: "#F59E0B",
    era: "3000–1000 BCE",
    visual: "map",
    title: "The Pharaoh's Intelligence Apparatus",
    hook: "Royal scribes tracked grain yields, trade movements, and military positioning across rival kingdoms — not as bureaucracy, but as strategic early warning.",
    points: [
      "The Pharaoh's vizier managed scribes who recorded competitor state outputs — grain stockpiles, military levies, and trade flows — structured competitive data updated seasonally",
      "Egyptian traders in foreign markets returned with intelligence on pricing, supply, and political stability alongside goods — commercial and intelligence functions deliberately merged",
      "When Egypt's intelligence network degraded under weak pharaohs, invasions followed predictably — the Hyksos, Sea Peoples, and Assyrians all exploited an Egypt that had stopped watching",
    ],
    cta: "Systematic monitoring always outperforms episodic curiosity.",
    priority: 2,
  },

  {
    id: "hist-sun-tzu",
    type: "history",
    badge: "HISTORY",
    accent: "#10b981",
    era: "500 BCE",
    visual: "book",
    title: "Sun Tzu and the Doctrine of Knowing",
    hook: "Sun Tzu devoted an entire chapter of The Art of War to intelligence. Strategy without foreknowledge is guesswork — and guesswork is a luxury only the losing side can afford.",
    points: [
      "Sun Tzu identified five categories of intelligence agents — no single source is sufficient, but five overlapping sources produce a picture the enemy cannot obscure",
      "His axiom 'know the enemy and know yourself' is operational doctrine, not philosophy. Armies that followed it consistently defeated numerically superior forces",
      "The Greeks applied the same principle at Marathon (490 BCE): runners monitored Persian camp movements for days before the battle, not just the famous sprint to Athens afterward",
    ],
    cta: "Five overlapping sources still produce clarity no single channel can.",
    priority: 3,
  },

  {
    id: "hist-roman",
    type: "history",
    badge: "HISTORY",
    accent: "#ef4444",
    era: "100 BCE – 400 CE",
    visual: "map",
    title: "The Roman Information Network",
    hook: "Rome's greatest advantage was not its legions — it was the cursus publicus, a courier and intelligence network spanning 80,000 km of road. Rome received intelligence in days. Rivals took weeks.",
    points: [
      "The cursus publicus reduced intelligence lag from weeks to days across three continents — a systematic time advantage over every regional competitor",
      "Roman merchants were legally encouraged to report on foreign market conditions, pricing, and political stability — commercial intelligence treated as a public good",
      "When the network degraded in the 3rd century CE through cost-cutting and neglect, Rome's response time slowed proportionally. The empire fell to ignorance, not superior force",
    ],
    cta: "Intelligence infrastructure scales. Episodic awareness does not.",
    priority: 4,
  },

  {
    id: "hist-medieval",
    type: "history",
    badge: "HISTORY",
    accent: "#8b5cf6",
    era: "1000–1400 CE",
    visual: "glass",
    title: "Siege Intelligence and the Art of Knowing a Castle",
    hook: "Medieval siege warfare was won or lost before the first stone was thrown. The commander who had mapped water sources and estimated garrison strength needed superior information, not superior numbers.",
    points: [
      "Siege commanders sent merchants and craftsmen ahead to assess fortifications — wall thickness, gate mechanisms, and supply levels reported months before engagement",
      "Saladin's campaigns succeeded through intelligence on castle water supply — sieges that would have taken years were resolved in weeks by cutting the one irreplaceable resource",
      "The castles that never fell shared one feature: their lords invested in external intelligence networks, not just thicker walls. Foreknowledge tripled effective defensive strength",
    ],
    cta: "The defender who knows an attack is coming has already won half the siege.",
    priority: 5,
  },

  {
    id: "hist-medici",
    type: "history",
    badge: "HISTORY",
    accent: "#f97316",
    era: "1400–1550 CE",
    visual: "deal",
    title: "The Medici Intelligence Machine",
    hook: "Medici agents across 16 European cities sent weekly dispatches on commodity prices, political alliances, and rival banker movements — not correspondence, but structured intelligence.",
    points: [
      "Medici 'factors' in every major trading city reported exchange rates, competitor liquidity, and political risk — delivered weekly via the most reliable courier network in Europe",
      "When Cosimo learned the Albizzi family planned his exile, he had weeks to prepare. What appeared to be political luck was systematic information advantage",
      "Rival banking houses that lacked equivalent networks repeatedly mispriced risk and were caught by movements the Medici had already anticipated. Intelligence was the moat, not capital",
    ],
    cta: "Superior intelligence, not superior capital, has always been the durable moat.",
    priority: 6,
  },

  {
    id: "hist-walsingham",
    type: "history",
    badge: "HISTORY",
    accent: "#64748b",
    era: "1570–1590 CE",
    visual: "glass",
    title: "Walsingham and the First Modern Intelligence Service",
    hook: "Francis Walsingham maintained 70 agents across 30 countries from personal funds. His advantage was systematic collection when rivals relied on rumour.",
    points: [
      "Walsingham used a layered source model: merchants, diplomats, and double-agents each provided different signal types, synthesised into a single threat picture updated weekly",
      "The Babington Plot (1586) was read in real time through intercepted correspondence for months before Walsingham allowed it to reach legally actionable treason",
      "The Spanish Armada (1588) was no surprise — Walsingham tracked the fleet's assembly for two years through agents in Spanish ports. England prepared because it never stopped watching",
    ],
    cta: "Systematic monitoring produces strategic certainty. Luck is not a strategy.",
    priority: 7,
  },

  {
    id: "hist-pinkerton",
    type: "history",
    badge: "HISTORY",
    accent: "#0891b2",
    era: "1850–1900 CE",
    visual: "store",
    title: "Industrial Espionage and the Birth of Commercial Intelligence",
    hook: "The Pinkerton Agency built its business on monitoring competitor activity for industrial clients. The intelligence function moved from states to corporations for the first time.",
    points: [
      "Carnegie, Vanderbilt, and Rockefeller used commercial intelligence to track competitor pricing, hiring, and plant expansions — signals tracked months before they became public",
      "Railroad espionage in the 1870s became so systematic that entire informant networks embedded in competitor operations — what we now call competitive intelligence was simply 'knowing your rivals'",
      "Companies that declined to invest in monitoring were systematically disadvantaged — reacting to shifts others had anticipated months earlier",
    ],
    cta: "The companies that watched first always paid less for the same advantage.",
    priority: 8,
  },

  {
    id: "hist-wwi-signals",
    type: "history",
    badge: "HISTORY",
    accent: "#dc2626",
    era: "1914–1918",
    visual: "clock",
    title: "The Zimmermann Telegram and the Signal That Changed a War",
    hook: "In January 1917, British intelligence intercepted a German telegram proposing a military alliance with Mexico. One intercepted signal brought the United States into World War I.",
    points: [
      "Room 40 had been decoding German communications since 1914 — the Zimmermann interception was the product of three years of continuous signal collection infrastructure, not luck",
      "The delay in revealing the telegram was strategic: Room 40 constructed a cover story to protect decryption capability while still acting on the intelligence",
      "Germany sent the telegram assuming its communications were secure. The risk of assuming your signals are invisible is that someone has already broken the channel",
    ],
    cta: "The signal gap has always existed. The question is who reads it.",
    priority: 9,
  },

  {
    id: "hist-cold-war",
    type: "history",
    badge: "HISTORY",
    accent: "#6366f1",
    era: "1950–1980",
    visual: "server",
    title: "When Competitive Intelligence Became State Doctrine",
    hook: "The Cold War industrialised competitive intelligence. Both superpowers built entire agencies dedicated to monitoring competitor outputs. Structured collection became infrastructure, not a luxury.",
    points: [
      "The CIA produced daily threat assessments from hundreds of signals — economic outputs, military movement, political language — synthesised into a single prioritised picture for the President",
      "Soviet industrial espionage acquired Western technology primarily through open-source collection, trade shows, and publications — publicly available signals Western companies assumed no one was reading",
      "The agencies that succeeded shared one property with businesses that survive disruption: they were permanently watching, not episodically curious",
    ],
    cta: "Permanent monitoring always outperforms periodic review.",
    priority: 10,
  },

  {
    id: "toys-r-us",
    type: "history",
    badge: "HISTORY",
    accent: "#F59E0B",
    era: "2000–2006",
    visual: "store",
    title: "The Toy Store That Handed Amazon Its Playbook",
    hook: "In 2000, Toys R Us outsourced its entire e-commerce operation to Amazon — giving Amazon full visibility into toy category demand and fulfillment patterns. By 2006, Amazon competed directly with every toy retailer on Earth.",
    points: [
      "Toys R Us granted Amazon access to buyer demand and fulfillment data in exchange for a revenue share that never built competitive capability",
      "Amazon listed competing brands on the same platform, violating exclusivity — by the time litigation completed, Amazon had learned everything it needed",
      "The signals were visible: warehouse expansions, third-party seller growth, and logistics investment were all public movements available to anyone watching",
    ],
    cta: "The signals of capability transfer are always visible before the leverage is applied.",
    priority: 9,
  },

  {
    id: "blockbuster",
    type: "history",
    badge: "HISTORY",
    accent: "#EF4444",
    era: "1997–2010",
    visual: "chart",
    title: "The Video Store That Watched Netflix Arrive",
    hook: "Netflix mailed Blockbuster its business plan in 1997. Blockbuster passed. By 2010, Netflix had 20 million subscribers and Blockbuster had filed for bankruptcy. The signals were never missing — the attention was.",
    points: [
      "Blockbuster's $800M late-fee revenue was exactly what Netflix was positioned to eliminate. Leadership couldn't see past the line item protecting them",
      "Netflix grew 600% between 2003 and 2007. Blockbuster responded in 2006 — after 6 million subscribers were already locked into a habit loop",
      "The behaviour change was measurable: online sign-ups, DVD-by-mail adoption, and streaming tests were all trackable before the transition became irreversible",
    ],
    cta: "Growth signals are always visible before they become revenue lines you can no longer defend.",
    priority: 10,
  },

  {
    id: "kodak",
    type: "history",
    badge: "HISTORY",
    accent: "#3B82F6",
    era: "1975–2012",
    visual: "camera",
    title: "The Company That Invented Digital — Then Buried It",
    hook: "Kodak engineer Steve Sasson invented the first digital camera in 1975. Kodak classified the project and returned to selling film. They had the intelligence. They chose the margin.",
    points: [
      "Kodak's own research predicted digital's disruption timeline in the 1990s. Leadership had the intelligence and suppressed it to protect film revenue",
      "By 2003, digital cameras outsold film globally. Kodak spent 8 years watching the transition at measurable speed, building capability too slowly to compete",
      "Kodak held 1,000+ digital imaging patents and licensed them to the companies that displaced them — royalty income instead of market position",
    ],
    cta: "Intelligence that reaches analysts but not decision-makers is intelligence that failed.",
    priority: 9,
  },

  {
    id: "nokia",
    type: "history",
    badge: "HISTORY",
    accent: "#8B5CF6",
    era: "2005–2013",
    visual: "phone",
    title: "The Phone Giant That Never Saw the Touchscreen Coming",
    hook: "In 2007, Nokia controlled 49% of the global mobile market. By 2013, they sold their phone division to Microsoft for a fraction of peak value. The technology existed. The organisational will did not.",
    points: [
      "Nokia's labs had working touchscreen prototypes as early as 2001 — years before iPhone. The gap was organisational, not technical",
      "When Apple launched, Nokia's public response was confidence. Internally, executives acknowledged Symbian was uncompetitive and the app ecosystem would define mobile",
      "Nokia's failure was not lack of intelligence — it was a structure that couldn't act on what it knew. Signals reached analysts but stopped at the boardroom door",
    ],
    cta: "Intelligence that cannot reach decision-makers is intelligence that has already failed.",
    priority: 10,
  },

  {
    id: "myspace",
    type: "history",
    badge: "HISTORY",
    accent: "#06B6D4",
    era: "2005–2009",
    visual: "map",
    title: "The Social Network That Gave Facebook a Blueprint",
    hook: "In 2005, MySpace sold to News Corp for $580M with 25 million users. In 2011, it sold again for $35M. Every relevant signal was public and trackable.",
    points: [
      "Facebook's growth velocity was visible from 2006: college rollout speed, 2.5x engagement, and API partnerships all signalled a platform strategy MySpace wasn't executing",
      "MySpace responded to Facebook's simplicity by adding features — increasing complexity exactly when users were choosing clarity. Each response made the product worse",
      "News Corp monetized MySpace as an advertising vehicle rather than a social platform — a fundamental misread of competitor intent that Facebook exploited",
    ],
    cta: "Competitor moves read as strategy reveal more than the same moves read as features.",
    priority: 8,
  },

  {
    id: "borders",
    type: "history",
    badge: "HISTORY",
    accent: "#F59E0B",
    era: "1997–2011",
    visual: "book",
    title: "The Bookstore That Outsourced Its Future to Amazon",
    hook: "In 2001, Borders outsourced its entire online operation to Amazon. In 2011, it filed for bankruptcy. Amazon became the world's largest bookseller. Borders gave them the roadmap.",
    points: [
      "Borders gave Amazon full visibility into book buyer demand and customer segments in exchange for a revenue share that never built competitive infrastructure",
      "Amazon's signals from 2001 to 2010 were consistent: warehouse announcements, Kindle development (public from 2004), and digital rights acquisitions. Borders tracked none as strategic movement",
      "Borders' e-reader launch (Kobo, 2010) came 3 years after Kindle. The competitive window opened and closed with no signal capture",
    ],
    cta: "Capability acquisitions define who owns the next category — and they are always visible early.",
    priority: 8,
  },

  {
    id: "blackberry",
    type: "history",
    badge: "HISTORY",
    accent: "#A78BFA",
    era: "2007–2012",
    visual: "phone",
    title: "The Keyboard That Refused to Disappear",
    hook: "In 2009, BlackBerry controlled 20% of the US smartphone market. By 2012, under 5%. The CEO dismissed iPhone's battery life in 2007 — and the organisation stopped watching.",
    points: [
      "BlackBerry's enterprise lock-in was a false moat. They classified consumer smartphones as separate from enterprise — until users started bringing iPhones to work",
      "Apple's App Store (2008) was the decisive movement. BlackBerry App World launched 11 months later — enough for iOS to lock 50,000 apps and developer loyalty",
      "App Store submission volume, iOS activation rates, and BYOD policy shifts were all observable. BlackBerry categorised them as 'consumer' rather than 'threat'",
    ],
    cta: "Categorising a signal as irrelevant does not make the threat go away.",
    priority: 8,
  },

  {
    id: "sears",
    type: "history",
    badge: "HISTORY",
    accent: "#64748B",
    era: "1996–2018",
    visual: "store",
    title: "The World's First Amazon, Undone by Its Own Catalogue",
    hook: "In 1894, Sears invented catalogue delivery. In 2018, they filed for bankruptcy — displaced by a company doing exactly that, online. The capability gap was a choice.",
    points: [
      "Sears had functioning e-commerce before Amazon was profitable. They had the capability but not the commitment to cannibalise store traffic",
      "Amazon's signals from 1999 to 2010 — warehouse expansion, Prime loyalty, third-party marketplace, AWS — were all public. Sears responded to none at strategic scale",
      "By 2010, Sears generated $44B revenue with no technology infrastructure, no loyalty platform, and no modern fulfilment. Amazon had built all three",
    ],
    cta: "Infrastructure signals are visible long before they become competitive moats.",
    priority: 7,
  },

  {
    id: "yahoo-google",
    type: "history",
    badge: "HISTORY",
    accent: "#F97316",
    era: "1998–2004",
    visual: "glass",
    title: "The Search Giant That Said No to Larry Page",
    hook: "In 2002, Yahoo could have acquired Google for $1 billion. In 2008, Google was worth $150 billion. Yahoo tracked Google's growth and still misread its trajectory.",
    points: [
      "Yahoo's team had full visibility into Google's search quality, advertiser growth, and API expansion from 2000 to 2004. The intelligence existed — the framing was wrong",
      "Yahoo classified Google as a 'search utility.' Every product launch (AdWords, Gmail, Maps, News) signalled the classification was incorrect. Yahoo underreacted to each",
      "The failed acquisition valued Google at 2002 revenue, not trajectory. A momentum model would have shown Google as the highest-velocity node in the field",
    ],
    cta: "Trajectory reveals more than position. Today's momentum is tomorrow's market.",
    priority: 9,
  },

  {
    id: "tower-records",
    type: "history",
    badge: "HISTORY",
    accent: "#EF4444",
    era: "2001–2006",
    visual: "book",
    title: "The Music Empire That Heard iTunes Coming",
    hook: "Tower Records' 2001 annual report named digital distribution as a primary risk. In 2006, they liquidated 89 stores. The signal was in their own filings — and was not acted on.",
    points: [
      "iTunes launched in 2003 with 200,000 tracks. Tower's response: 'People still want CDs.' By December, iTunes had sold 25 million songs — measurable velocity, ignored",
      "Napster's 80 million users (2001) was the most important signal Tower ever received. Their response was litigation, not understanding the demand signal",
      "Tower's strategy documents show detailed awareness of digital economics. They tracked it, modelled it, and chose to optimise stores instead of building digital capability",
    ],
    cta: "Intelligence without action is a filing cabinet, not a strategic advantage.",
    priority: 7,
  },

  {
    id: "palm",
    type: "history",
    badge: "HISTORY",
    accent: "#34D399",
    era: "2000–2010",
    visual: "phone",
    title: "The Pocket Computer That Defined Smartphones — Then Missed Them",
    hook: "Palm's Treo 600 (2003) was arguably the first true smartphone. By 2010, Palm sold to HP with 1% market share. They invented the category and watched it be taken.",
    points: [
      "Palm saw the app ecosystem concept in 2003 but never built a developer platform with the commitment Apple brought to the App Store — the distribution model that won",
      "Between 2005 and 2008, Windows Mobile, BlackBerry, and iPhone captured the narrative. Palm tracked feature parity but missed the platform shift visible in developer adoption",
      "Palm's webOS (2009) arrived 23 months after iPhone — after developer attention and consumer habit were locked. Timing windows close faster than organisations move",
    ],
    cta: "Timing windows in competitive markets close faster than organisations can react without advance warning.",
    priority: 6,
  },

  {
    id: "britannica",
    type: "history",
    badge: "HISTORY",
    accent: "#06B6D4",
    era: "1995–2012",
    visual: "book",
    title: "The Encyclopedia That Watched Wikipedia Happen in Real Time",
    hook: "Britannica had been the world's knowledge authority for 244 years. In 2012, they discontinued print — ended by a free website built by volunteers. The disruption was trackable from day one.",
    points: [
      "Wikipedia launched in 2001 with 20,000 articles. By 2004, 1 million. By 2006, 5 million. Britannica's response: 'We maintain expert contributors.' The velocity was a visible signal",
      "The threat was not accuracy — it was access. Britannica tracked correctness and missed the distribution signal: free, everywhere, instantly. The wrong metric governed the response",
      "Britannica's online service launched in 1994, seven years before Wikipedia. They chose a premium paywall while the competitor chose free. Strategy failed, not capability",
    ],
    cta: "Tracking the wrong signal is indistinguishable from tracking nothing at all.",
    priority: 7,
  },

  {
    id: "mapquest",
    type: "history",
    badge: "HISTORY",
    accent: "#94A3B8",
    era: "2004–2008",
    visual: "map",
    title: "The World's Dominant Map, Outflanked in 18 Months",
    hook: "In 2004, MapQuest served 65% of all online map requests. By 2008, Google Maps had taken most of that. The transition took 18 months, signalled by a public API announcement most teams dismissed.",
    points: [
      "Google Maps launched in 2005 with an open API. MapQuest had no API strategy. Distribution was the competitive movement, not the product",
      "Within 6 months, thousands of developers built on Google Maps. MapQuest tracked this as a feature, not as a distribution advantage that would become permanent",
      "Satellite view, Street View, and mobile integration were all trackable expansions. MapQuest's parent treated each as a feature gap, not a platform strategy",
    ],
    cta: "Platform strategy reveals more about competitive intent than any feature comparison.",
    priority: 6,
  },

  {
    id: "netscape",
    type: "history",
    badge: "HISTORY",
    accent: "#10B981",
    era: "1995–2001",
    visual: "server",
    title: "The Browser That Invented the Web — Then Lost It to Free",
    hook: "Netscape made the web accessible. Microsoft released IE for free, bundled it with Windows, and within 4 years held 96% market share. The strategy was announced in writing.",
    points: [
      "Gates' 1995 memo 'The Internet Tidal Wave' declared the browser a primary strategic priority. The memo was public. Netscape focused on enterprise instead of addressing the distribution signal",
      "The 'free bundled with OS' signal was visible from IE 1.0 in 1995. Netscape kept pricing at $39 for 3 more years, dropping to zero only after the signal was obvious",
      "Netscape's antitrust victory in 2001 confirmed the harm — but market share was already gone. Legal responses operate on a different timescale than competitive ones",
    ],
    cta: "Distribution signals always precede market share shifts. The writing is usually literal.",
    priority: 8,
  },

  // ── FEATURE ──────────────────────────────────────────────────────────────────

  {
    id: "feat-radar-gravity",
    type: "feature",
    badge: "SYSTEM",
    accent: "#00B4FF",
    era: "Interface",
    visual: "radar-gravity",
    title: "The Radar Gravity Field",
    hook: "Every node occupies a position earned by its evidence record. Momentum is computed from signals and movement confidence — nothing on the radar is decorative.",
    points: [
      "Nodes are placed using the golden angle spiral — a pattern from nature that prevents clustering regardless of competitor count, giving every node equal visual weight",
      "Four momentum states govern appearance: Cooling (<1.5), Stable (1.5–3), Rising (3–5), Accelerating (≥5). Color, size, and echo ring speed all encode momentum simultaneously",
      "The critical alert requires all five conditions at once: momentum ≥ 7, signals_7d ≥ 3, confidence ≥ 0.70, confirmed movement type, and last seen within 48 hours",
    ],
    cta: "Every node position is a fact, not an estimate.",
    priority: 9,
  },

  {
    id: "feat-signal-detection",
    type: "feature",
    badge: "SYSTEM",
    accent: "#3B82F6",
    era: "Detection",
    visual: "signal-detection",
    title: "The Signal Detection Engine",
    hook: "The system detects strategic signals by isolating what changed, validating the change is meaningful, and classifying what it means. The filter is as important as the detector.",
    points: [
      "Pages are segmented into logical sections. Each is diffed against a stable baseline — not the previous snapshot — reducing noise from A/B tests and dynamic content",
      "Two noise filters run before any signal is created: whitespace-only changes and dynamic-content changes (timestamps, UTM params) are suppressed before scoring begins",
      "A signal is created only when a real change in a meaningful section crosses a confidence threshold. Most page changes never become signals. That ratio is intentional",
    ],
    cta: "When a signal appears, it has passed three gates. It is real.",
    priority: 10,
  },

  {
    id: "feat-confidence",
    type: "feature",
    badge: "SYSTEM",
    accent: "#A78BFA",
    era: "Detection",
    visual: "confidence-model",
    title: "The Confidence Model",
    hook: "Every signal carries a 0-1 confidence score built from four factors: section type, page class, recency, and observation count. Below 0.35, signals are suppressed entirely.",
    points: [
      "Section type is primary: a pricing block starts at 0.85 confidence; a generic text section at 0.25. Page type predicts signal quality before content analysis",
      "Page class adds +0.08 for high-value pages, recency adds up to +0.15, repeated observations add up to +0.15 — a composite reflecting actual evidence weight",
      "Pressure_index at 5.0 overrides the confidence gate: high activity elevates pending_review signals to interpretation even when individual confidence is moderate",
    ],
    cta: "Every signal in the feed has earned its place through evidence, not heuristics.",
    priority: 8,
  },

  {
    id: "feat-movement",
    type: "feature",
    badge: "SYSTEM",
    accent: "#8B5CF6",
    era: "Analysis",
    visual: "movement-detection",
    title: "When Signals Become Strategy",
    hook: "A single pricing change is evidence. Three pricing changes in 10 days, combined with a repositioned headline and a new enterprise section — that is a movement. Metrivant waits for the pattern.",
    points: [
      "Movements require a minimum of 2 correlated signals within a 14-day window for the same competitor. A single anomaly never becomes a movement — the system waits for confirmation",
      "Movement type is classified with a confidence score and velocity measure: pricing shift, product expansion, market reposition, enterprise push, or ecosystem expansion",
      "Every confirmed movement receives an analyst narrative: what happened, why it matters, and what to watch next — grounded in the underlying signals",
    ],
    cta: "Patterns reveal strategy. Individual events rarely do.",
    priority: 9,
  },

  {
    id: "feat-pressure",
    type: "feature",
    badge: "SYSTEM",
    accent: "#EF4444",
    era: "Analysis",
    visual: "pressure-index",
    title: "The Pressure Index",
    hook: "Each competitor carries a pressure index from 0.0 to 10.0 — a weighted, time-decaying measure of activity intensity. Not a signal count. A measure of current momentum.",
    points: [
      "Signals decay exponentially with age: a signal from 14 days ago contributes only 5.5% of a same-day signal's weight. The pressure index is always about now, not history",
      "Ambient events — press mentions, hiring announcements, product updates — feed the index without requiring interpretation. A competitor can accumulate pressure without triggering a signal",
      "When a competitor's index reaches 5.0, their pending_review signals are promoted to active interpretation. High ambient activity accelerates signal processing",
    ],
    cta: "Pressure precedes movement. The index shows who is about to move.",
    priority: 8,
  },

  {
    id: "feat-page-classes",
    type: "feature",
    badge: "SYSTEM",
    accent: "#34D399",
    era: "Detection",
    visual: "page-classes",
    title: "How Monitoring Frequency Is Assigned",
    hook: "Pricing pages change rarely but critically. Blog pages change often but ambiguously. Each class is monitored at the frequency it deserves.",
    points: [
      "High-value pages (pricing, changelog, newsroom) are crawled every hour at :02 past — a pricing change can be detected within 58 minutes of going live on a competitor's site",
      "Standard pages (homepage, features) run every 3 hours. Ambient pages (blog, careers) run every 30 minutes — feeding activity signals rather than strategic diffs",
      "High-value pages receive a +0.08 confidence bonus on all their signals, because evidence from a pricing page is structurally more reliable than evidence from a blog post",
    ],
    cta: "Not all pages carry equal intelligence value. Frequency should match importance.",
    priority: 7,
  },

  {
    id: "feat-sector",
    type: "feature",
    badge: "SYSTEM",
    accent: "#06B6D4",
    era: "Analysis",
    visual: "sector-intelligence",
    title: "Sector-Wide Pattern Analysis",
    hook: "Every Monday at 07:00 UTC, a cross-competitor analysis runs across all signals from the last 30 days — surfacing patterns no single competitor's feed would reveal.",
    points: [
      "The analysis pivots all signals by section_type across every tracked competitor, structured to surface which change types are happening simultaneously across your competitive field",
      "GPT-4o identifies sector_trends (multiple competitors converging on similar moves) and divergences (competitors moving opposite to peers, often signalling a strategic differentiation bet)",
      "Every sector insight is post-linked to real signal IDs — every trend is traceable to specific page changes on specific competitor sites, not generated from inference alone",
    ],
    cta: "Cross-competitor patterns are invisible when you analyse one competitor at a time.",
    priority: 7,
  },

  {
    id: "feat-brief",
    type: "feature",
    badge: "SYSTEM",
    accent: "#F59E0B",
    era: "Delivery",
    visual: "weekly-brief",
    title: "Monday Intelligence Brief",
    hook: "Every Monday at 10:00 UTC, a competitive intelligence brief arrives — assembled from the week's movements, sector analysis, and competitor narratives, grounded in evidence.",
    points: [
      "The brief is assembled from pre-generated artifacts: sector intelligence summaries, movement narratives, and per-competitor radar narratives — not by re-analyzing raw signals. Assembly is fast and evidence-complete",
      "Output is structured: headline summary, competitors analyzed, major moves, strategic implications, and recommended actions. Every section traces back to observed page changes",
      "The brief arrives via email from briefs@metrivant.com and is available in-app on the Briefs page — covering only intelligence generated since the previous brief, never recycling old data",
    ],
    cta: "Monday morning intelligence should arrive before the working week begins.",
    priority: 8,
  },

  {
    id: "feat-velocity",
    type: "feature",
    badge: "SYSTEM",
    accent: "#F97316",
    era: "Analysis",
    visual: "signal-velocity",
    title: "Signal Velocity — The Leading Indicator",
    hook: "A competitor silent for 30 days who suddenly emits 6 signals in 72 hours is more alarming than one who emits 2 signals a week for a year. Velocity measures rate of change — not total count.",
    points: [
      "Velocity is computed as signals per day within a rolling window, weighted toward recency. A burst of signals in a short window registers higher velocity than the same number spread over a month",
      "Velocity feeds momentum_score: a high-velocity competitor accelerates toward the radar center faster than a high-count competitor with gradual consistent activity",
      "Velocity is a leading indicator. When it spikes, movement confirmation typically follows within 3–7 days. The radar shows the acceleration before the label is confirmed",
    ],
    cta: "The velocity spike is the leading indicator. It arrives before the label is confirmed.",
    priority: 8,
  },

  {
    id: "feat-repair",
    type: "feature",
    badge: "SYSTEM",
    accent: "#10B981",
    era: "System",
    visual: "selector-repair",
    title: "The System That Fixes Itself",
    hook: "When a competitor redesigns their website, CSS selectors may break. The auto-repair system detects drift, re-fetches live HTML, and proposes corrected selectors without losing the monitoring chain.",
    points: [
      "Drift detection triggers when a (page, section) pair shows 3 consecutive suspect validations within 72 hours — Metrivant recognises it may be missing real changes due to structural breakage",
      "The repair process re-fetches live HTML and sends it to GPT-4o-mini with a description of what the section should contain. The model proposes a new CSS selector, validated with Cheerio before storage",
      "Repairs are never auto-applied. Every suggestion goes to operator review — because a wrong selector silently creates a monitoring gap, and data integrity depends on human confirmation",
    ],
    cta: "A monitoring system that cannot detect its own degradation is not trustworthy.",
    priority: 6,
  },

  {
    id: "feat-alert",
    type: "feature",
    badge: "SYSTEM",
    accent: "#EF4444",
    era: "Delivery",
    visual: "critical-alert",
    title: "Five Conditions. One Alert.",
    hook: "A critical alert fires only when five conditions are simultaneously true. This is not caution — it is the architecture of trust. One false alarm destroys more attention than ten missed signals.",
    points: [
      "The five conditions: momentum ≥ 7, signals in 7 days ≥ 3, movement confidence ≥ 0.70, a confirmed movement type, and last seen within 48 hours. All five simultaneously — no partial triggers",
      "When an alert fires: radar rings pulse in the movement's color, the alerted node blooms, and a navigation path to the Strategy page appears. At most one alert fires per radar load — the highest-momentum qualifier wins",
      "Session dedup prevents the same alert from firing twice: competitor_id + last_movement_seen_at. You see each alert once, and only when the intelligence is genuinely fresh",
    ],
    cta: "One false alarm destroys more attention than ten missed signals.",
    priority: 9,
  },

  {
    id: "feat-momentum",
    type: "feature",
    badge: "SYSTEM",
    accent: "#00B4FF",
    era: "Interface",
    visual: "momentum-states",
    title: "Reading the Radar's Visual Language",
    hook: "Every competitor is in one of four states. Each changes the node's colour, size, echo ring speed, and glow intensity. The visual language is a data encoding.",
    points: [
      "Cooling (<1.5): slate, slow echo. Stable (1.5–3): green, moderate echo. Rising (3–5): amber, faster echo. Accelerating (≥5): red, fastest echo at 1.5-second cycle. Speed is data",
      "Signal type micro-shapes appear inside active nodes: a dash for pricing shifts, a plus for product expansion, a diamond for repositioning, an arrow for enterprise push — the primary signal type visible at a glance",
      "Confidence-proportional opacity: nodes with movement confidence above 0.65 render at full opacity; nodes with lower confidence appear at 75–88%. Your eye naturally focuses where the evidence is strongest",
    ],
    cta: "Read the radar. The pattern of who is moving is the intelligence.",
    priority: 7,
  },

  {
    id: "feat-orbit-mode",
    type: "feature",
    badge: "SYSTEM",
    accent: "#818cf8",
    era: "Interface",
    visual: "radar-gravity",
    title: "ORBIT Mode — The Heliocentric Radar",
    hook: "In ORBIT mode, the highest-momentum competitor moves to the centre. Others orbit at radii determined by relative weight — inner orbits faster, outer slower, exactly as Kepler described.",
    points: [
      "Orbital periods follow Kepler's Third Law: T ∝ r^1.5 — inner shells complete a full orbit in 28 seconds, the outermost shell takes over three minutes. The physics is real, not decorative",
      "Shell assignment is deterministic: the top competitor occupies the centre, shells 1–4 hold the remaining competitors in mass order. When a competitor's momentum changes, they migrate shells — the radar reorganises live",
      "Hovering over a node pauses its shell so you can click precisely — the orbit freezes only for that shell while all others continue. Release the hover and it resumes from exactly where it was",
    ],
    cta: "Mass relationships are visible at a glance when gravity determines position.",
    priority: 5,
  },

  {
    id: "feat-pool-system",
    type: "feature",
    badge: "SYSTEM",
    accent: "#00B4FF",
    era: "Pipeline",
    visual: "chart",
    title: "Seven Signal Pools — Beyond Page Monitoring",
    hook: "Seven additive signal pools collect intelligence from newsroom feeds, job postings, investor announcements, product launches, procurement tenders, regulatory filings, and media coverage.",
    points: [
      "Pool signals carry source attribution — a hiring spike is classified differently from a pricing change. The confidence model prevents feed noise from polluting page-diff signals",
      "Cross-pool reconciliation boosts confidence when the same competitor appears in multiple pools within 24 hours — corroborated signals are more reliable than single-source ones",
      "Sequence detection flags multi-pool patterns: a press release, 15 engineering roles, and a regulatory filing in one week triggers convergence even if no single event crossed a threshold",
    ],
    cta: "The full competitive picture requires more than web monitoring alone.",
    priority: 6,
  },

  {
    id: "feat-context-evolution",
    type: "feature",
    badge: "SYSTEM",
    accent: "#f59e0b",
    era: "Intelligence",
    visual: "chart",
    title: "Competitor Context — The Evolving Hypothesis",
    hook: "For each competitor, the system maintains a living strategic hypothesis based on accumulated signal evidence. When that hypothesis shifts significantly, it triggers an alert — a pivot detected before the announcement.",
    points: [
      "After each interpretation batch, new signals are read in context of what the system already knows, updating the working theory of strategic intent",
      "When the updated hypothesis shares less than 50% overlap with the previous version, a potential strategic reorientation is flagged and emailed",
      "The was/now evidence block shows the exact transition — what was believed last week vs now — anchored to the specific signals that caused the shift",
    ],
    cta: "Events are data points. The strategic arc connecting them is the intelligence.",
    priority: 7,
  },

  {
    id: "feat-coverage-healing",
    type: "feature",
    badge: "SYSTEM",
    accent: "#10b981",
    era: "Reliability",
    visual: "chart",
    title: "The System That Heals Its Own Coverage",
    hook: "Pages move, URLs redirect, content migrates. The coverage healing system runs daily to detect broken monitoring paths and repair them automatically.",
    points: [
      "When a page enters an unresolved state — HTTP errors, challenge walls, or degradation — the system re-validates the URL, then discovers candidates from sitemaps and navigation",
      "Candidates are validated against content-pattern gates: sitemaps, legal pages, and single posts are rejected. Only pages matching the expected profile are committed",
      "Challenge-blocked pages are handled by a ScrapingBee fallback at fetch time — the healing system focuses on structural URL problems, not access problems",
    ],
    cta: "Coverage that degrades silently is coverage that has already failed.",
    priority: 8,
  },

  {
    id: "feat-sector-intel",
    type: "feature",
    badge: "SYSTEM",
    accent: "#818cf8",
    era: "Weekly",
    visual: "chart",
    title: "Sector Intelligence — The Monday Picture",
    hook: "Every Monday, a cross-competitor analysis runs across every tracked signal from the previous 30 days — identifying sector trends, divergences, and strategic patterns no single signal would surface.",
    points: [
      "Sector intelligence is synthesis, not summary: three rivals adjusting pricing in a month, two enterprise pushes and a market retreat, simultaneous launches in one category",
      "The brief assembles four artifact types — sector intelligence, movement summaries, per-competitor narratives, and media observations — composed into one analyst-grade document",
      "Delivered Monday morning so strategic review precedes the working week — structured preparation for what signals suggest is coming, not a reactive response",
    ],
    cta: "A week of automated monitoring, compressed into a single decision-ready picture.",
    priority: 9,
  },

  {
    id: "feat-signal-feedback",
    type: "feature",
    badge: "SYSTEM",
    accent: "#ef4444",
    era: "Calibration",
    visual: "chart",
    title: "Signal Feedback — Teaching the System What Matters",
    hook: "Every intelligence system produces noise. A feedback mechanism lets operators mark signals as valid, uncertain, or noise — feeding labels back into confidence calibration.",
    points: [
      "Operators mark signals with verdict and noise category from the ops dashboard. Feedback is stored per signal and used in brief generation to filter noise from synthesis",
      "Noise patterns are categorised: dynamic content, whitespace-only diffs, A/B test artefacts, cookie banners. Each category informs future diff suppression logic",
      "The calibration loop closes at the confidence model: page types and section types that consistently produce noise get suppressed earlier. The pipeline self-tunes",
    ],
    cta: "Every verdict makes the next signal more reliable. The system learns from correction.",
    priority: 10,
  },

  {
    id: "feat-tension-links",
    type: "feature",
    badge: "SYSTEM",
    accent: "#c084fc",
    era: "Strategy",
    visual: "radar-gravity",
    title: "Strategic Tension — Reading Convergence",
    hook: "When multiple competitors move in the same direction simultaneously, the radar draws tension filaments between them — encoding convergence intensity and the speed at which a market dynamic is compressing.",
    points: [
      "Links require shared movement type AND combined momentum of at least 1.5 — a gate that prevents low-confidence signals from creating false convergence indicators",
      "Opacity, dash gap, and colour saturation all scale with tension intensity — a glance distinguishes mild category overlap from acute competitive collision",
      "In ORBIT mode, filaments rotate with orbiting nodes — when high-momentum competitors in the same shell share a movement type, the dynamic is visible in motion",
    ],
    cta: "Convergence is visible in movement data before it appears in press releases.",
    priority: 11,
  },

  {
    id: "feat-pressure-index",
    type: "feature",
    badge: "SYSTEM",
    accent: "#f97316",
    era: "Mechanics",
    visual: "chart",
    title: "Pressure Index — The Urgency Scalar",
    hook: "The pressure index is a live urgency score that determines how aggressively pending signals are promoted. High-pressure competitors get faster interpretation and earlier promotion.",
    points: [
      "Pressure accumulates from weighted events: press mentions (0.30), hiring spikes (0.20), product updates (0.15) — each decayed exponentially so recent activity counts more",
      "At pressure 5.0, signals in pending_review (confidence 0.35-0.64) are promoted to pending for AI interpretation automatically, without operator action",
      "Bootstrap logic prevents deadlock: new competitors with zero interpreted signals get their highest-confidence pending_review promoted regardless of pressure",
    ],
    cta: "Interpretive effort should follow market urgency, not a fixed schedule.",
    priority: 12,
  },

  {
    id: "feat-pipeline-obs",
    type: "feature",
    badge: "SYSTEM",
    accent: "#38bdf8",
    era: "Operations",
    visual: "chart",
    title: "Pipeline Observability — Every Stage, Every Run",
    hook: "Every pipeline stage logs its execution: duration, status, signal counts, suppression rates, and anomalies. The pipeline is a glass box, not a black one.",
    points: [
      "Six stages emit structured events on every execution: snapshot, extraction, baseline, diff, signal, and interpretation. Each records duration, run_id, and metadata",
      "Sentry monitors every cron schedule independently — a missed 2am execution triggers an alert before anyone notices degraded morning coverage",
      "Anomaly detection fires automatically: 5+ diffs with 98% suppression triggers a warning. Section counts deviating 60% from the 5-snapshot average triggers extraction_drift",
    ],
    cta: "You cannot improve what you cannot see. A glass box, not a black one.",
    priority: 13,
  },

  {
    id: "feat-activity-echo",
    type: "feature",
    badge: "SYSTEM",
    accent: "#00B4FF",
    era: "Interface",
    visual: "radar-gravity",
    title: "Activity Echo — The Radar Remembers",
    hook: "When a competitor publishes a signal, its node emits a subtle expanding ripple. The echo fades over 48 hours — showing at a glance who has been active without reading a single number.",
    points: [
      "Echo intensity is proportional to recency: two hours ago pulses visibly, 40 hours barely registers. Decay matches the 48-hour activity window",
      "Nodes without recent activity render with a dashed orbit ring — a visual indication that the system is watching but the competitor has been quiet",
      "Ambient pulse lines connect the central emitter to the three freshest echo nodes — drawing attention to current activity without inspecting individual competitors",
    ],
    cta: "Position is history. Movement is intelligence.",
    priority: 14,
  },

  // ── SCIENCE ──────────────────────────────────────────────────────────────────

  {
    id: "sci-threat",
    type: "science",
    badge: "SCIENCE",
    accent: "#EF4444",
    era: "Neuroscience",
    visual: "brain",
    title: "The Threat Detection Circuit",
    hook: "The amygdala fires 40 milliseconds before the prefrontal cortex processes a threat. We detect danger before understanding it — but competitive threats move on timescales the amygdala was never designed for.",
    points: [
      "Preconscious threat detection evolved for predators in open savannah — stimuli in peripheral vision requiring immediate motor response. Competitive threats are the inverse: slow, indirect, and structural",
      "The threat circuit prioritises salient, sudden signals over gradual accumulation. A competitor's pricing page that changes 12% over 8 months triggers no neurological alarm in any human reviewer — but represents a confirmed strategic movement",
      "Systematic monitoring extends threat detection to the timescales where competitive threats actually operate — months and years, not milliseconds and seconds",
    ],
    cta: "The amygdala was designed for predators, not pricing pages.",
    priority: 9,
  },

  {
    id: "sci-asymmetry",
    type: "science",
    badge: "SCIENCE",
    accent: "#06B6D4",
    era: "Economics",
    visual: "asymmetry",
    title: "Information Asymmetry",
    hook: "Akerlof won the Nobel Prize for proving markets fail when one party knows more than the other. The company that knows its competitor's next move first wins more often than the one with the better product.",
    points: [
      "Knowing a competitor's next move first enables pre-emption or countering before the market settles. The intelligence window is the structural advantage",
      "Akerlof's 'market for lemons' model shows asymmetry creates rational disengagement. In strategy, executives stop acting on intelligence they can't source and verify",
      "The solution to asymmetry is always systematic collection, verification, and delivery of information to the disadvantaged party",
    ],
    cta: "The solution to asymmetry is always systematic collection and delivery.",
    priority: 8,
  },

  {
    id: "sci-loss",
    type: "science",
    badge: "SCIENCE",
    accent: "#F59E0B",
    era: "Behavioral Economics",
    visual: "loss-aversion",
    title: "Loss Aversion and Competitive Risk",
    hook: "Kahneman proved losses feel 2.5x more painful than equivalent gains feel pleasurable. Missing a competitor's move hurts more than capturing it early helps — but the asymmetry only becomes visible after it's too late.",
    points: [
      "Loss aversion creates systematic bias toward the status quo. Leaders who know a competitor is moving still prefer waiting for confirmation over acting early",
      "A team that misses a signal and loses share suffers visible pain. A team that acts early on a false signal suffers diffuse embarrassment. The asymmetry under-invests in early action",
      "If missing a true signal costs 2.5x acting on a false one, the confidence threshold for action should be lower than intuition suggests",
    ],
    cta: "If missing a true signal costs 2.5x acting on a false one, your threshold should be lower than intuition suggests.",
    priority: 8,
  },

  {
    id: "sci-availability",
    type: "science",
    badge: "SCIENCE",
    accent: "#8B5CF6",
    era: "Cognitive Psychology",
    visual: "availability",
    title: "The Availability Heuristic",
    hook: "Humans judge probability by how easily an example comes to mind. In competitive strategy, you systematically overestimate threats you've faced before and underestimate the ones you haven't.",
    points: [
      "Teams focus monitoring on companies they already know — incumbents faced, deals lost — while systematically underweighting new entrants and adjacent-category movers",
      "Novel threats by definition don't come to mind easily. The disrupting competitor almost always starts as someone you didn't track in a category you didn't consider adjacent",
      "Broad systematic monitoring is the structural override for availability bias — forcing attention onto what is happening, not what memory suggests is probable",
    ],
    cta: "The competitor that disrupts your market almost always starts as someone you didn't track.",
    priority: 7,
  },

  {
    id: "sci-pattern",
    type: "science",
    badge: "SCIENCE",
    accent: "#34D399",
    era: "Cognitive Neuroscience",
    visual: "pattern",
    title: "Pattern Recognition Before Conscious Thought",
    hook: "The visual cortex recognises patterns 150-200 milliseconds before the brain constructs conscious awareness. The pattern of movement is the intelligence, visible before analysis is complete.",
    points: [
      "Preattentive processing detects motion, colour change, and spatial clustering without directed attention. Size, colour, and position communicate threat level before you consciously read a number",
      "Expert pattern recognition — chess grandmasters, military commanders, fund managers — stores configurations and spots deviations. Baselines are configurations; diffs are deviations",
      "An accelerating node in red near the centre, pulsing fast, is distinguished from a cooling node at the periphery in under 200 milliseconds",
    ],
    cta: "The pattern of who is moving is the intelligence — visible before conscious analysis.",
    priority: 8,
  },

  {
    id: "sci-vigilance",
    type: "science",
    badge: "SCIENCE",
    accent: "#00B4FF",
    era: "Evolutionary Psychology",
    visual: "vigilance",
    title: "Competitive Vigilance — The Evolutionary Basis",
    hook: "For 99% of evolutionary history, failing to monitor for threats was fatal. The organisms that survived never stopped watching. That instinct is now mismatched to market competition's pace and scale.",
    points: [
      "In nature, dedicated lookouts maintain continuous observation while others feed. The cognitive cost is distributed. In competitive markets, this distribution almost always fails",
      "In organisations, monitoring is distributed across analyst teams, product managers, and sales. Signal leakage is enormous. No single person holds the full picture",
      "Evolutionary vigilance has one property modern competitive intelligence lacks: it is always on. Competitors do not pause because your cycle hasn't refreshed",
    ],
    cta: "Competitors do not pause their moves because your monitoring cycle hasn't refreshed.",
    priority: 9,
  },

  {
    id: "sci-sensemaking",
    type: "science",
    badge: "SCIENCE",
    accent: "#3B82F6",
    era: "Cognitive Science",
    visual: "sensemaking",
    title: "The Sensemaking Loop",
    hook: "Karl Weick showed that organisations construct meaning retrospectively — they act, observe consequences, then interpret. By the time you've made sense of a signal, the window to respond may have closed.",
    points: [
      "Sensemaking is inherently retrospective: signals that contradict the current story are deprioritised — not through malice, but through the mechanics of meaning-making",
      "The solution is prospective monitoring: tracking signals before a narrative is needed, creating an evidence archive that can be interrogated when a decision is required",
      "Signals created when changes are detected — not when someone decides to look — structurally eliminate the retrospective sensemaking problem",
    ],
    cta: "Evidence assembled after the fact is always biased toward the conclusion already drawn.",
    priority: 7,
  },

  {
    id: "sci-confirmation",
    type: "science",
    badge: "SCIENCE",
    accent: "#F97316",
    era: "Cognitive Psychology",
    visual: "confirmation",
    title: "Confirmation Bias in Competitive Strategy",
    hook: "We seek, interpret, and remember information that confirms what we already believe. The companies that most need intelligence — incumbents defending an existing model — are least likely to interpret it correctly.",
    points: [
      "Confirmation bias manifests as 'competitor fit' framing: incumbents assess new products against their own strengths, not weaknesses. The assessment always finds the new product lacking",
      "Nokia's engineers correctly assessed iPhone's battery life was inferior. True and irrelevant. The confirmation they sought led them to dismiss the app ecosystem signal",
      "Systematic monitoring creates a confirmation-resistant evidence base: the diff between before and after is not subject to interpretation until after it is observed",
    ],
    cta: "The diff is what happened. Analysis may be biased. The signal is not.",
    priority: 8,
  },

  {
    id: "sci-dopamine",
    type: "science",
    badge: "SCIENCE",
    accent: "#A78BFA",
    era: "Neuroscience",
    visual: "dopamine",
    title: "The Intelligence Habit — Dopamine and Routine",
    hook: "Dopamine is the molecule of anticipated reward, not pleasure. Regular, reliable intelligence delivery creates a habit loop that changes how teams make competitive decisions.",
    points: [
      "The habit loop (cue, routine, reward) applies to intelligence consumption: a reliable Monday brief creates a cue, a reading routine, and a reward when it confirms or challenges assumptions",
      "Teams that receive regular intelligence become more likely to act on it. The routine creates a cognitive frame for decisions that sporadic intelligence does not",
      "A system that surfaces new signals reliably creates the same anticipation loop that makes great information products habitual — applied to strategic data",
    ],
    cta: "The cadence is as important as the content. Routine creates the decision frame.",
    priority: 7,
  },

  {
    id: "sci-planning",
    type: "science",
    badge: "SCIENCE",
    accent: "#EF4444",
    era: "Behavioral Economics",
    visual: "planning-fallacy",
    title: "The Planning Fallacy",
    hook: "Humans systematically underestimate how long their own plans take while overestimating friction in competitors' plans. In markets, this asymmetry is the margin of defeat.",
    points: [
      "The fallacy is strongest for complex multi-stage projects — exactly what competitive movements represent. Incumbents believe they have more time because they apply optimistic timelines to their own plans",
      "Blockbuster applied realistic friction to Netflix's projections while applying optimistic timelines to their own response. The 3-year asymmetry was their undoing",
      "The antidote is tracking from first signal: velocity shows how fast a competitor is actually moving, not how fast you estimate they could",
    ],
    cta: "Velocity tracking shows how fast a competitor is actually moving, not how fast you estimate they could.",
    priority: 8,
  },

  {
    id: "sci-working-memory",
    type: "science",
    badge: "SCIENCE",
    accent: "#64748B",
    era: "Cognitive Neuroscience",
    visual: "working-memory",
    title: "Working Memory and the Limits of Attention",
    hook: "Working memory holds approximately 4 chunks simultaneously. Your competitive landscape has 15-25 actors generating multiple signals per week. The mismatch is structural, not a failure of diligence.",
    points: [
      "Miller's Law established 7 plus or minus 2 capacity; Cowan refined it to 4 chunks. No team can model 20 competitors' movements in working memory — the limitation is neurological, not organisational",
      "Cognitive offloading — extending memory to external systems — is how humans have managed complexity since writing. The radar holds competitive state so working memory can hold strategy",
      "Each interface element — intelligence drawer, momentum states, signal feed — is a working memory extension, representing one 'chunk' the brain can rapidly parse",
    ],
    cta: "No human brain can hold 20 competitors in working memory. External systems can.",
    priority: 7,
  },

  {
    id: "sci-exposure",
    type: "science",
    badge: "SCIENCE",
    accent: "#06B6D4",
    era: "Social Psychology",
    visual: "exposure",
    title: "The Mere Exposure Effect and Competitive Blindness",
    hook: "Zajonc showed that repeated exposure increases positive evaluation regardless of objective quality. Familiarity with competitors distorts threat assessment in a systematic, measurable way.",
    points: [
      "Teams rate familiar competitors as more threatening than equivalently positioned new entrants. The known threat is overweighted; the novel threat is underweighted",
      "Long-tenured competitors lose signal freshness: teams stop registering changes because the pattern feels familiar. A company that 'always changes pricing' stops triggering alarm",
      "Signal-based monitoring overrides the effect: a pricing page diff has the same weight whether from a 2-year rival or a 2-week new entrant",
    ],
    cta: "Signal-based monitoring evaluates evidence, not familiarity.",
    priority: 7,
  },

  {
    id: "sci-game-theory",
    type: "science",
    badge: "SCIENCE",
    accent: "#6366f1",
    era: "Mathematics",
    visual: "chart",
    title: "Game Theory and the Prisoner's Dilemma of Market Intelligence",
    hook: "Nash proved that in competitive systems, rational strategy depends on what you believe every other player will do. Competitive intelligence is belief formation under uncertainty, not information collection.",
    points: [
      "In the prisoner's dilemma, both parties defect because neither knows the other's move. Markets work the same: opacity destroys value for everyone except the first mover",
      "Nash equilibria shift when information asymmetry is reduced. Better intelligence means choosing optimal responses to actual actions rather than assumptions",
      "The value of intelligence is the reduction in strategic uncertainty. Knowing a pricing move is coming creates more options than discovering it after launch",
    ],
    cta: "Reducing strategic uncertainty changes the equilibrium for every player.",
    priority: 10,
  },

  {
    id: "sci-signalling",
    type: "science",
    badge: "SCIENCE",
    accent: "#10b981",
    era: "Biology / Economics",
    visual: "chart",
    title: "Signalling Theory — What Competitors Reveal Without Intending To",
    hook: "Spence won the Nobel for showing that costly signals — expensive to fake — reliably communicate genuine intent. Competitors constantly emit them through public actions. Reading them correctly removes the need for a spy.",
    points: [
      "A pricing page redesign requires engineering, copywriting, and legal review. The investment communicates genuine intent to reposition, not a test",
      "Hiring 15 enterprise sales specialists takes months and significant capital. You cannot fake this signal. You can only watch for it",
      "The gap between press releases and costly public actions is where intelligence lives. Statements are cheap. Hiring patterns and product changes are expensive — and therefore true",
    ],
    cta: "Costly signals — hiring, engineering investment, page changes — cannot be faked.",
    priority: 11,
  },

  {
    id: "sci-network-effects",
    type: "science",
    badge: "SCIENCE",
    accent: "#f59e0b",
    era: "Economics",
    visual: "chart",
    title: "Network Effects and the Tipping Point Problem",
    hook: "Metcalfe's Law: network value grows with the square of connected users. The company that crosses the tipping point first doesn't just win the current round — it makes future rounds nearly impossible.",
    points: [
      "Tipping points rarely announce themselves. They appear as gradual acceleration in growth, partnerships, and integrations — individually normal, collectively indicating runaway scale",
      "Blockbuster, MySpace, and Yahoo all faced competitors accumulating network effects while appearing small. The moment those networks crossed tipping points, the game was already over",
      "The response window for network effect accumulation is measured in months, not years. By the time it's visible in revenue, the structural advantage is locked in",
    ],
    cta: "By the time a network effect is visible in revenue, the structural advantage is already locked in.",
    priority: 12,
  },

  {
    id: "sci-ooda",
    type: "science",
    badge: "SCIENCE",
    accent: "#ef4444",
    era: "Military Science",
    visual: "chart",
    title: "The OODA Loop — Decision Speed as Competitive Advantage",
    hook: "Boyd's OODA loop — Observe, Orient, Decide, Act — explains why faster decision cycles consistently defeat slower ones, even with inferior forces.",
    points: [
      "Boyd's insight: advantage is not better decisions but faster loops. By the time a slow competitor orients to a change, a fast one has already acted and moved to the next cycle",
      "Observe and Orient are where intelligence creates structural advantage: detecting a move in hours rather than weeks compounds across every decision cycle",
      "Manual monitoring fails at Observe — by the time a human analyst has noticed, read, and synthesised competitor activity, the fastest response window has often closed",
    ],
    cta: "The company that completes the loop faster wins by default.",
    priority: 13,
  },

  {
    id: "sci-red-queen",
    type: "science",
    badge: "SCIENCE",
    accent: "#dc2626",
    era: "Evolutionary Biology",
    visual: "chart",
    title: "The Red Queen Effect — Running to Stay Still",
    hook: "Van Valen's Red Queen: species that stop adapting go extinct even if their environment hasn't changed — because their competitors have. Markets work identically.",
    points: [
      "Competitive fitness is relative, not absolute. A company that maintains capabilities while competitors improve is effectively degrading",
      "Blockbuster, Kodak, and Borders did not stand still. They continued investing. They failed because they improved more slowly than their environment and did not detect the gap",
      "The practical implication: monitoring cadence must match the rate competitors generate meaningful signals. Annual reviews are Red Queen failure in slow motion",
    ],
    cta: "The market benchmark moves whether or not you do. Monitoring must be continuous.",
    priority: 14,
  },

  {
    id: "sci-bayesian",
    type: "science",
    badge: "SCIENCE",
    accent: "#8b5cf6",
    era: "Statistics",
    visual: "chart",
    title: "Bayesian Updating and the Intelligence Advantage",
    hook: "Bayes described a method for updating beliefs as new evidence arrives. Companies that continuously update their model of competitor strategy make better predictions than those that form a view once and hold it.",
    points: [
      "A single signal is weak evidence. Ten correlated signals from different sources are strong. Each confirming signal adjusts the posterior probability that the strategic hypothesis is correct",
      "Companies that fail to update suffer prior lock-in: a view formed two years ago, maintained despite contradicting evidence. The Bayesian term is refusing to update the posterior",
      "Base confidence from section type, adjusted by recency, observation count, page class, and corroboration. Each update moves the estimate closer to the true probability of genuine intent",
    ],
    cta: "Beliefs about competitors should update with evidence, not with annual reviews.",
    priority: 15,
  },

  {
    id: "sci-information-cascade",
    type: "science",
    badge: "SCIENCE",
    accent: "#0891b2",
    era: "Behavioural Economics",
    visual: "chart",
    title: "Information Cascades — When the Market Moves in Herds",
    hook: "Bikhchandani showed that rational agents can collectively make catastrophically wrong decisions when they rely on observing each other rather than their own information. This is how entire markets miss publicly available signals.",
    points: [
      "In cascades, each participant assumes aggregate behaviour reflects superior information. The result: herding that ignores strong private signals in favour of the crowd — even when wrong",
      "Systematic signal monitoring lets an organisation maintain an independent assessment regardless of consensus — and act before the cascade corrects",
      "The companies that profited from Blockbuster's decline and Nokia's collapse were not smarter. They were less dependent on consensus and trusted their own monitoring",
    ],
    cta: "Independent signal infrastructure prevents strategy from being captive to consensus.",
    priority: 16,
  },

  {
    id: "sci-temporal-discounting",
    type: "science",
    badge: "SCIENCE",
    accent: "#f97316",
    era: "Psychology",
    visual: "chart",
    title: "Temporal Discounting and the Long-Game Problem",
    hook: "Temporal discounting: humans systematically undervalue future outcomes relative to immediate ones. In strategy, this manifests as chronic underinvestment in early-warning systems.",
    points: [
      "Companies cancel intelligence programs during cost reviews because the ROI is invisible in normal conditions — the counterfactual of crises avoided is unobservable",
      "Value is concentrated in the 5% of cases where a signal arrives early enough to change strategy. Evaluating on confirmatory value alone guarantees underinvestment",
      "Companies that maintained intelligence through downturns were consistently better positioned when shifts arrived. The cost is linear; the value is episodic and convex",
    ],
    cta: "The cost of intelligence is linear. The value is episodic and convex.",
    priority: 17,
  },

  {
    id: "sci-cognitive-ease",
    type: "science",
    badge: "SCIENCE",
    accent: "#64748b",
    era: "Psychology",
    visual: "chart",
    title: "Cognitive Ease and the Familiarity Trap",
    hook: "Kahneman showed the brain rates familiar information as more true regardless of accuracy. In competitive strategy, this creates systematic bias toward known competitors while novel entrants are persistently underrated.",
    points: [
      "Netflix, digital cameras, and e-commerce were not unknown — they were cognitively discounted. The problem was cognitive ease favouring the familiar threat model over the unfamiliar one",
      "Momentum-ranked displays counteract the bias: competitors are presented by current activity, not familiarity. A quiet incumbent and an active new entrant get equal visual treatment",
      "Structured monitoring presents evidence before judgement. A pricing page signal arrives before the mental model has time to classify it as unimportant",
    ],
    cta: "Familiarity is not safety. The familiar threat model is often the wrong one.",
    priority: 18,
  },

  {
    id: "sci-weak-signals",
    type: "science",
    badge: "SCIENCE",
    accent: "#00B4FF",
    era: "Strategic Management",
    visual: "chart",
    title: "Weak Signal Theory — Detecting the Future Before It Arrives",
    hook: "Ansoff's weak signal theory (1975): strategic threats arrive as faint, ambiguous signals long before they become trends. The companies that survive are those that started watching earliest.",
    points: [
      "A weak signal is a genuine precursor that hasn't yet accumulated enough corroboration. The art is distinguishing it from noise before industry consensus forms",
      "Most corporate disasters were preceded by weak signals visible for 12-36 months. They were ignored because organisational incentives punished early action on uncertain evidence",
      "The pending_review confidence tier (0.35-0.64) implements weak signal theory: signals below certainty are held and observed, accumulating corroboration until pressure promotes them",
    ],
    cta: "Weak signals should be held and observed, not discarded because they aren't yet obvious.",
    priority: 19,
  },
];
