import { NextResponse } from "next/server";
import { generateBrief, buildBriefEmailHtml, getDailyQuote, type BriefContent } from "../../../lib/brief";

export const maxDuration = 90;
import { sendEmail, FROM_BRIEFS } from "../../../lib/email";
import { createServiceClient } from "../../../lib/supabase/service";
import { captureException, flush } from "../../../lib/sentry";

// captureCheckIn is server-only in @sentry/nextjs and must not live in lib/sentry.ts
// (which is also client-bundled via app/app/error.tsx). API routes are server-only, so
// the direct SDK import here is safe from Turbopack's client-bundle static analysis.
function captureCheckIn(status: "in_progress" | "ok" | "error", checkInId?: string): string | undefined {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (require("@sentry/nextjs") as any).captureCheckIn?.({
      monitorSlug: "generate-brief",
      status,
      ...(checkInId ? { checkInId } : {}),
    }) as string | undefined;
  } catch { return undefined; }
}
import { writeCronHeartbeat } from "../../../lib/cronHeartbeat";

// ── Artifact types ─────────────────────────────────────────────────────────────

type MovementArtifact = {
  competitor_name:      string;
  movement_type:        string;
  movement_summary:     string;
  strategic_implication: string | null;
  confidence_level:     string | null;
  confidence:           number;
};

type ActivityArtifact = {
  competitor_name: string;
  narrative:       string;
  signal_count:    number;
};

type NarrativeArtifact = {
  theme_label:      string;
  article_count:    number;
  source_count:     number;
  confidence_score: number;
  last_detected_at: string;
};

// ── Helpers ────────────────────────────────────────────────────────────────────

function weekLabel(date: Date): string {
  return date.toLocaleDateString("en-US", {
    month: "long",
    day:   "numeric",
    year:  "numeric",
  });
}

function isAuthorized(request: Request): boolean {
  const secret = process.env.CRON_SECRET;
  if (!secret) return false;
  const auth = request.headers.get("authorization");
  return auth === `Bearer ${secret}`;
}

/**
 * Builds a markdown rendering of BriefContent for email plain-text fallback
 * and the brief_markdown column. Purely deterministic — no LLM.
 */
function buildBriefMarkdown(
  brief:      BriefContent,
  weekLabel:  string,
  date:       Date = new Date(),
  narratives: NarrativeArtifact[] = []
): string {
  const quote = getDailyQuote(date);
  const lines: string[] = [
    `# Intelligence Brief — ${weekLabel}`,
    ``,
    `> "${quote.text}"`,
    `> — ${quote.attribution}`,
    ``,
    brief.headline,
    ``,
  ];

  if (brief.major_moves.length > 0) {
    lines.push(`## Major Moves`, ``);
    for (const m of brief.major_moves) {
      lines.push(`**${m.competitor}** [${m.severity.toUpperCase()}]`);
      lines.push(m.move);
      lines.push(``);
    }
  }

  if (brief.strategic_implications.length > 0) {
    lines.push(`## Strategic Implications`, ``);
    for (const imp of brief.strategic_implications) {
      lines.push(`**${imp.theme}**`);
      lines.push(imp.implication);
      lines.push(``);
    }
  }

  if (brief.recommended_actions.length > 0) {
    lines.push(`## Recommended Actions`, ``);
    for (const a of brief.recommended_actions) {
      lines.push(`- [${a.priority.toUpperCase()}] ${a.action}`);
    }
    lines.push(``);
  }

  if (brief.closing_insight) {
    lines.push(`## Strategic Insight`, ``);
    lines.push(`_${brief.closing_insight}_`);
    lines.push(``);
  }

  // Deterministic Market Context section — appended from sector_narratives.
  // Not generated by the LLM; purely assembled from stored cluster data.
  if (narratives.length > 0) {
    lines.push(`## Market Context`, ``);
    lines.push(`Active sector narratives from ${narratives.length} media cluster${narratives.length !== 1 ? "s" : ""}:`, ``);
    for (const n of narratives) {
      const date = n.last_detected_at.slice(0, 10);
      const confPct = Math.round(n.confidence_score * 100);
      lines.push(
        `- **${n.theme_label}** — ${n.article_count} articles across ${n.source_count} publications` +
        ` (${confPct}% confidence, last seen ${date})`
      );
    }
    lines.push(``);
  }

  return lines.join("\n");
}

/**
 * Builds the GPT-4o user prompt from pre-generated artifacts.
 * No raw signals — only sector_intelligence, movement narratives, radar narratives.
 */
function buildArtifactPrompt(
  weekLabel:      string,
  sectorSummary:  string | null,
  movements:      MovementArtifact[],
  activity:       ActivityArtifact[],
  narratives:     NarrativeArtifact[] = []
): string {
  const lines: string[] = [
    `Week of ${weekLabel}`,
    ``,
  ];

  if (sectorSummary) {
    lines.push(`Sector Intelligence (cross-competitor analysis):`, ``);
    lines.push(sectorSummary);
    lines.push(``);
  }

  if (movements.length > 0) {
    lines.push(`Competitor Movements (last 7 days, ordered by confidence):`, ``);
    movements.forEach((m, i) => {
      const confLabel = m.confidence_level ?? `${Math.round(m.confidence * 100)}%`;
      lines.push(`${i + 1}. ${m.competitor_name} — ${m.movement_type} [${confLabel}]`);
      lines.push(`   Movement: ${m.movement_summary}`);
      if (m.strategic_implication) {
        lines.push(`   Implication: ${m.strategic_implication}`);
      }
      lines.push(``);
    });
  }

  if (activity.length > 0) {
    lines.push(`Competitor Activity Summaries:`, ``);
    for (const a of activity) {
      lines.push(`- ${a.competitor_name} (${a.signal_count} signal${a.signal_count !== 1 ? "s" : ""}): ${a.narrative}`);
    }
    lines.push(``);
  }

  // Sector media narratives as background market context (not competitor-specific).
  if (narratives.length > 0) {
    lines.push(`Sector Media Narratives (background context — active themes in sector press):`, ``);
    for (const n of narratives) {
      const date = n.last_detected_at.slice(0, 10);
      lines.push(
        `- "${n.theme_label}" — ${n.article_count} articles from ${n.source_count} sources` +
        ` (confidence ${n.confidence_score.toFixed(2)}, last ${date})`
      );
    }
    lines.push(``);
  }

  lines.push(`Generate the weekly intelligence brief based only on the above synthesized intelligence.`);
  return lines.join("\n");
}

// ── Core generation ────────────────────────────────────────────────────────────

async function runGeneration(): Promise<NextResponse> {
  const openaiKey = process.env.OPENAI_API_KEY;
  if (!openaiKey) {
    captureCheckIn("error");
    await flush();
    return NextResponse.json(
      { error: "OPENAI_API_KEY not configured" },
      { status: 500 }
    );
  }

  const checkInId = captureCheckIn("in_progress");

  const runStart  = Date.now();
  const siteUrl   = process.env.NEXT_PUBLIC_SITE_URL ?? "https://metrivant.com";
  const week      = weekLabel(new Date());
  const supabase  = createServiceClient();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;

  // 1 — Load all organisations
  const { data: orgs, error: orgsError } = await sb
    .from("organizations")
    .select("id, owner_id, sector");

  if (orgsError) {
    captureException(orgsError, { route: "generate-brief", step: "fetch_orgs" });
    captureCheckIn("error", checkInId);
    await flush();
    return NextResponse.json({ error: "Failed to fetch organizations" }, { status: 500 });
  }

  if (!orgs || orgs.length === 0) {
    await writeCronHeartbeat(supabase, "/api/generate-brief", "ok", Date.now() - runStart, 0);
    captureCheckIn("ok", checkInId);
    await flush();
    return NextResponse.json({ ok: true, briefs_generated: 0, emails_sent: 0, message: "No organizations" });
  }

  // 2 — Load all auth users once (for email lookup per org owner)
  let userEmailById: Map<string, string> = new Map();
  try {
    const { data: { users } } = await supabase.auth.admin.listUsers({ perPage: 500 });
    userEmailById = new Map(
      users.filter((u) => u.email).map((u) => [u.id, u.email!])
    );
  } catch (err) {
    captureException(err instanceof Error ? err : new Error(String(err)), {
      route: "generate-brief", step: "fetch_users",
    });
    // Non-fatal — briefs are generated even if emails can't be sent
  }

  // 3 — Per-org brief generation
  let briefsGenerated = 0;
  let emailsSent      = 0;
  let totalSignals    = 0;

  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

  for (const org of orgs as { id: string; owner_id: string; sector: string | null }[]) {
    try {

      // ── Tracked competitor IDs ────────────────────────────────────────────
      const { data: trackedRows } = await sb
        .from("tracked_competitors")
        .select("competitor_id")
        .eq("org_id", org.id)
        .not("competitor_id", "is", null);

      const competitorIds = [...new Set(
        ((trackedRows ?? []) as { competitor_id: string }[]).map((r) => r.competitor_id)
      )];

      if (competitorIds.length === 0) continue;

      // ── Competitor names ──────────────────────────────────────────────────
      const { data: compRows } = await supabase
        .from("competitors")
        .select("id, name")
        .in("id", competitorIds);

      const nameById = new Map<string, string>(
        ((compRows ?? []) as { id: string; name: string }[]).map((c) => [c.id, c.name])
      );

      // ── Sector intelligence (latest row within 7 days for this org) ───────
      let sectorSummary: string | null = null;
      try {
        const { data: siRows } = await sb
          .from("sector_intelligence")
          .select("summary")
          .eq("org_id", org.id)
          .gte("created_at", sevenDaysAgo)
          .order("created_at", { ascending: false })
          .limit(1);

        sectorSummary = (siRows?.[0]?.summary as string | undefined) ?? null;
      } catch { /* Non-fatal */ }

      // ── Movement artifacts (movement_summary populated, last 7d, LIMIT 10) ─
      const movements: MovementArtifact[] = [];
      try {
        const { data: movRows } = await sb
          .from("strategic_movements")
          .select("competitor_id, movement_type, movement_summary, strategic_implication, confidence_level, confidence")
          .in("competitor_id", competitorIds)
          .not("movement_summary", "is", null)
          .gte("last_seen_at", sevenDaysAgo)
          .order("confidence", { ascending: false })
          .limit(10);

        for (const r of (movRows ?? []) as {
          competitor_id:        string;
          movement_type:        string;
          movement_summary:     string | null;
          strategic_implication: string | null;
          confidence_level:     string | null;
          confidence:           number;
        }[]) {
          if (!r.movement_summary) continue;
          movements.push({
            competitor_name:      nameById.get(r.competitor_id) ?? r.competitor_id,
            movement_type:        r.movement_type,
            movement_summary:     r.movement_summary,
            strategic_implication: r.strategic_implication,
            confidence_level:     r.confidence_level,
            confidence:           r.confidence,
          });
        }
      } catch { /* Non-fatal */ }

      // ── Activity artifacts (latest radar_narrative per competitor) ────────
      const activity: ActivityArtifact[] = [];
      try {
        const { data: narRows } = await sb
          .from("radar_narratives")
          .select("competitor_id, narrative, signal_count, created_at")
          .in("competitor_id", competitorIds)
          .order("created_at", { ascending: false })
          .limit(competitorIds.length * 2); // dedup in code

        const seenNarr = new Set<string>();
        for (const n of (narRows ?? []) as {
          competitor_id: string;
          narrative:     string;
          signal_count:  number;
        }[]) {
          if (seenNarr.has(n.competitor_id)) continue;
          seenNarr.add(n.competitor_id);
          activity.push({
            competitor_name: nameById.get(n.competitor_id) ?? n.competitor_id,
            narrative:       n.narrative,
            signal_count:    n.signal_count,
          });
        }
      } catch { /* Non-fatal */ }

      // ── Sector media narratives (last 14 days, max 5, confidence DESC) ────
      const narratives: NarrativeArtifact[] = [];
      if (org.sector) {
        try {
          const narrativeCutoff = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString();
          const { data: narRows } = await sb
            .from("sector_narratives")
            .select("theme_label, article_count, source_count, confidence_score, last_detected_at")
            .eq("sector", org.sector)
            .gte("last_detected_at", narrativeCutoff)
            .order("confidence_score", { ascending: false })
            .limit(5);

          for (const n of (narRows ?? []) as NarrativeArtifact[]) {
            narratives.push(n);
          }
        } catch { /* Non-fatal */ }
      }

      // Skip if no artifacts to synthesize
      if (!sectorSummary && movements.length === 0 && activity.length === 0) continue;

      const signalCount = activity.reduce((sum, a) => sum + a.signal_count, 0);
      totalSignals += signalCount;

      // ── Build competitor list for generateBrief (minimal — names + movements) ──
      // We pass a lightweight RadarCompetitor-compatible array derived from artifacts.
      // The AI prompt is built from artifacts via the overridden user prompt path.
      // generateBrief is called directly with a pre-built prompt.
      const userPrompt    = buildArtifactPrompt(week, sectorSummary, movements, activity, narratives);
      const aiStart       = Date.now();
      const briefContent  = await generateBriefFromArtifacts(openaiKey, userPrompt);
      const aiDurationMs  = Date.now() - aiStart;
      const now           = new Date();

      // Record AI latency to pipeline_events — best-effort, fire-and-forget
      void supabase.from("pipeline_events").insert({
        stage:       "brief_generation",
        status:      "success",
        duration_ms: aiDurationMs,
        metadata:    {
          model:         "gpt-4o",
          batch_size:    movements.length + activity.length,
          org_id:        org.id,
        },
      });

      // ── Deterministic markdown rendering ──────────────────────────────────
      const briefMarkdown = buildBriefMarkdown(briefContent, week, now, narratives);

      // ── Persist to Supabase ───────────────────────────────────────────────
      const { data: briefRow, error: insertError } = await sb
        .from("weekly_briefs")
        .insert({
          org_id:         org.id,
          content:        briefContent,
          signal_count:   signalCount,
          generated_at:   new Date().toISOString(),
          sector_summary: sectorSummary,
          movements:      movements,
          activity:       activity,
          brief_markdown: briefMarkdown,
        })
        .select("id")
        .single();

      if (insertError) {
        captureException(insertError, {
          route: "generate-brief",
          step: "brief_insert",
          org_id: org.id,
        });
        // Non-fatal — continue to next org
      } else {
        briefsGenerated++;
        void briefRow;
      }

      // ── Send email to org owner ───────────────────────────────────────────
      const ownerEmail = userEmailById.get(org.owner_id);
      if (ownerEmail) {
        const emailHtml = buildBriefEmailHtml(briefContent, week, siteUrl, now);
        const result = await sendEmail({
          to:      ownerEmail,
          subject: `Your weekly competitor intelligence brief — ${week}`,
          html:    emailHtml,
          from:    FROM_BRIEFS,
        });
        if (result.ok) emailsSent++;
      }
    } catch (orgErr) {
      captureException(orgErr instanceof Error ? orgErr : new Error(String(orgErr)), {
        route: "generate-brief",
        step: "per_org_generation",
        org_id: org.id,
      });
      // Non-fatal — continue to next org
    }
  }

  // 4 — PostHog event (best-effort)
  const posthogKey = process.env.POSTHOG_API_KEY;
  if (posthogKey) {
    void fetch("https://app.posthog.com/capture", {
      method:  "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        api_key:     posthogKey,
        event:       "brief_generated",
        distinct_id: "system",
        properties:  {
          orgs_processed:   orgs.length,
          briefs_generated: briefsGenerated,
          emails_sent:      emailsSent,
          total_signals:    totalSignals,
          week,
        },
      }),
    });
  }

  await writeCronHeartbeat(supabase, "/api/generate-brief", "ok", Date.now() - runStart, emailsSent);
  captureCheckIn("ok", checkInId);
  await flush();

  return NextResponse.json({
    ok:               true,
    week,
    orgs_processed:   orgs.length,
    briefs_generated: briefsGenerated,
    emails_sent:      emailsSent,
    total_signals:    totalSignals,
  });
}

// ── OpenAI call — artifact-based prompt ───────────────────────────────────────

const SYSTEM_PROMPT = `\
You are a senior competitive intelligence analyst producing a precise, actionable weekly brief.
Your job: turn synthesized competitor intelligence into grounded, specific analysis — not general commentary.

Return valid JSON matching this exact schema — nothing else:
{
  "headline": "One sentence naming the dominant competitive development this week — specific companies and actions, no hedging",
  "competitors_analyzed": ["array of competitor names that had meaningful activity"],
  "major_moves": [
    {
      "competitor": "competitor name",
      "move": "one sentence stating exactly what changed and why it matters — name the product, price, or market change specifically",
      "severity": "high | medium | low"
    }
  ],
  "strategic_implications": [
    {
      "theme": "2–4 word theme label",
      "implication": "1–2 sentences of precise causal reasoning — what this move signals about the competitor's intent and what it means for your position"
    }
  ],
  "recommended_actions": [
    {
      "action": "one concrete action sentence — name the specific thing to build, change, accelerate, or stop",
      "priority": "high | medium | low"
    }
  ],
  "closing_insight": "one sentence strategic takeaway — the single most important thing to hold in mind this week"
}

Rules:
- Max 5 items in major_moves
- Max 3 items in strategic_implications
- Max 3 items in recommended_actions
- high = act this week, medium = act this month, low = awareness only
- Write only from the intelligence provided — do not apply general knowledge about these companies' histories
- Write like a practitioner, not a consultant — favor precise observation over hedged inference
- Never use: "it's worth noting", "it is important to", "in conclusion", "leverage", "synergy", "holistic"
- Never recommend "monitoring" as an action — recommend a decision or a build
- If no significant activity occurred, return empty arrays and a factual headline`;

async function generateBriefFromArtifacts(
  apiKey:     string,
  userPrompt: string
): Promise<BriefContent> {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model:           "gpt-4o",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user",   content: userPrompt },
      ],
      response_format: { type: "json_object" },
      temperature:     0.25,
      max_tokens:      1400,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`OpenAI error ${res.status}: ${body}`);
  }

  const json = (await res.json()) as {
    choices: Array<{ message: { content: string } }>;
    usage?:  { prompt_tokens: number; completion_tokens: number };
  };

  let parsed: Partial<BriefContent>;
  try {
    parsed = JSON.parse(json.choices[0].message.content) as Partial<BriefContent>;
  } catch {
    throw new Error("OpenAI returned non-JSON content");
  }

  return {
    headline:               parsed.headline ?? "No significant competitive activity detected this week.",
    competitors_analyzed:   parsed.competitors_analyzed   ?? [],
    major_moves:            parsed.major_moves            ?? [],
    strategic_implications: parsed.strategic_implications ?? [],
    recommended_actions:    parsed.recommended_actions    ?? [],
    closing_insight:        parsed.closing_insight,
    model:                  "gpt-4o",
    prompt_tokens:          json.usage?.prompt_tokens,
    completion_tokens:      json.usage?.completion_tokens,
  };
}

// ── Route handlers ─────────────────────────────────────────────────────────────

// GET — called by Vercel cron (Authorization: Bearer {CRON_SECRET} injected automatically)
export async function GET(request: Request): Promise<NextResponse> {
  if (!isAuthorized(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  return runGeneration();
}

// POST — for manual triggers during development
export async function POST(request: Request): Promise<NextResponse> {
  if (!isAuthorized(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  return runGeneration();
}
